export const events = [
  {
    id: "1",
    title: "Festival de Jazz en el Parque",
    date: "15 de Mayo, 2025",
    time: "17:00 - 22:00",
    location: "Parque Forestal, Santiago",
    image: "/placeholder.svg?height=300&width=400",
    category: "Música",
    description:
      "Disfruta de una tarde llena de música con los mejores artistas de jazz nacionales e internacionales. Habrá food trucks, zona de picnic y actividades para toda la familia.",
    coordinates: [-33.4369, -70.6445] as [number, number],
  },
  {
    id: "2",
    title: "Maratón de Santiago 2025",
    date: "5 de Mayo, 2025",
    time: "07:00 - 14:00",
    location: "Plaza Italia, Santiago",
    image: "/placeholder.svg?height=300&width=400",
    category: "Deportes",
    description:
      "La carrera más importante de Chile. Recorrido de 42K, 21K y 10K por las principales calles de Santiago. Inscripciones abiertas hasta el 20 de abril.",
    coordinates: [-33.4372, -70.6356] as [number, number],
  },
  {
    id: "3",
    title: "Feria Gastronómica Internacional",
    date: "12-14 de Mayo, 2025",
    time: "12:00 - 22:00",
    location: "Parque Araucano, Las Condes",
    image: "/placeholder.svg?height=300&width=400",
    category: "Gastronomía",
    description:
      "Más de 50 stands con comida de todo el mundo. Showcookings, catas de vino, talleres para niños y mucho más en un ambiente familiar.",
    coordinates: [-33.4103, -70.5751] as [number, number],
  },
  {
    id: "4",
    title: "Exposición de Arte Contemporáneo",
    date: "1-30 de Mayo, 2025",
    time: "10:00 - 19:00",
    location: "Centro Cultural La Moneda",
    image: "/placeholder.svg?height=300&width=400",
    category: "Arte y cultura",
    description:
      "Una muestra de los artistas emergentes más destacados de Latinoamérica. Pinturas, esculturas, instalaciones y arte digital en un recorrido inmersivo.",
    coordinates: [-33.4433, -70.6534] as [number, number],
  },
  {
    id: "5",
    title: "Concierto Sinfónico bajo las Estrellas",
    date: "20 de Mayo, 2025",
    time: "20:00 - 22:30",
    location: "Cerro San Cristóbal",
    image: "/placeholder.svg?height=300&width=400",
    category: "Música",
    description:
      "La Orquesta Filarmónica de Santiago presenta un repertorio de música clásica y bandas sonoras de películas en un entorno natural único.",
    coordinates: [-33.4251, -70.6311] as [number, number],
  },
  {
    id: "6",
    title: "Feria de Emprendedores Locales",
    date: "8-9 de Mayo, 2025",
    time: "11:00 - 20:00",
    location: "Parque Bicentenario, Vitacura",
    image: "/placeholder.svg?height=300&width=400",
    category: "Otros",
    description:
      "Conoce y apoya a más de 100 emprendedores chilenos. Productos artesanales, orgánicos, moda sostenible, decoración y mucho más.",
    coordinates: [-33.3903, -70.6043] as [number, number],
  },
  {
    id: "7",
    title: "Conferencia de Tecnología e Innovación",
    date: "18-19 de Mayo, 2025",
    time: "09:00 - 18:00",
    location: "Centro de Convenciones, Santiago",
    image: "/placeholder.svg?height=300&width=400",
    category: "Tecnología",
    description:
      "El evento más importante de tecnología en Chile. Charlas, workshops y networking con los líderes de la industria tecnológica nacional e internacional.",
    coordinates: [-33.4189, -70.6042] as [number, number],
  },
  {
    id: "8",
    title: "Trekking al Cajón del Maipo",
    date: "25 de Mayo, 2025",
    time: "08:00 - 17:00",
    location: "Cajón del Maipo",
    image: "/placeholder.svg?height=300&width=400",
    category: "Aire libre",
    description:
      "Disfruta de un día en contacto con la naturaleza. Recorrido guiado por los senderos más impresionantes del Cajón del Maipo con vistas panorámicas.",
    coordinates: [-33.6075, -70.3456] as [number, number],
  },
  {
    id: "9",
    title: "Festival de Cine Independiente",
    date: "22-28 de Mayo, 2025",
    time: "Varios horarios",
    location: "Diversos cines de Santiago",
    image: "/placeholder.svg?height=300&width=400",
    category: "Arte y cultura",
    description:
      "Proyección de películas independientes de todo el mundo. Incluye charlas con directores, actores y productores invitados.",
    coordinates: [-33.436, -70.635] as [number, number],
  },
]
