// Definición de rutas de la aplicación
export const ROUTES = {
  HOME: "/",
  EVENTS: "/events",
  ALL_EVENTS: "/all-events",
  EVENT_DETAILS: (id: string) => `/events/${id}`,
  ORGANIZERS: "/organizers",
  ORGANIZER_DETAILS: (id: string) => `/organizers/${id}`,
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTER_ORGANIZER: "/register/organizer",
  DASHBOARD: "/dashboard",
  DASHBOARD_PROFILE: "/dashboard/profile",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_ORGANIZERS: "/admin/organizers",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_CHAT: "/admin/chat",
  ADMIN_REPORTS: "/admin/reports",
  ORGANIZER: "/organizer",
  ORGANIZER_EVENTS: "/organizer/events",
  ORGANIZER_PROFILE: "/organizer/profile",
  ORGANIZER_MESSAGES: "/organizer/messages",
  ORGANIZER_CREATE_EVENT: "/organizer/events/create",
}
